# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8363714414501d5d8708c3f6f1edba2b74d9dbb886af3dc09ea89d4f8bb3d1178a6c61602b42e193c3a08b5d850bf142cff05d2c21b52c28fe4ecce46f44a7ab

test:
  secret_key_base: b2420831ef8aea6163c47b200f5a2b6de9640a9d70ad349a3ed54e5cce09d02edd0194c21396a40a02d5bff13556417f29e0238d57f17be7f33d47485cd2102d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
